;     The contents of this file are subject to the Mozilla Public License
;     Version 1.0 (the "License"); you may not use this file except in
;     compliance with the License. You may obtain a copy of the License at
;     http://www.mozilla.org/MPL/
;
;     Software distributed under the License is distributed on an "AS IS"
;     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
;     License for the specific language governing rights and limitations
;     under the License.

            title   'ATINIT - Start CP/M'

            cseg


            mov     cx,ds
            mov     es,cx
            call    cls
            call    print_cpm_ver
            lea     si, msg_rtc
            call    print_str

include atclock.a86

cls:
            push    ax
            push    bx
            push    cx
            mov     dx,27
            mov     cl,02h            
            int     0E0h    
            mov     dx,'E'
            mov     cl,02h            
            int     0E0h    
            pop     cx
            pop     bx
            pop     ax
            ret

print_cpm_ver:
            push    si
            push    ax
            push    bx
            push    cx
            push    dx
            mov     cx,0Ch
            int     0E0h
            and     ah,04h
            jz      print_ver_base
            lea     si, msg_ver_cc
            call    print_str  
print_ver_base:
            lea     si, msg_ver_hdr
            call    print_str  
            xor     ah,ah
            mov     bx,16
            mov     dl,al
            mov     cl,4
            shr     al, cl
            and     al,0Fh
            call    print_uint16
            mov     al,'.'
            call    print_char
            mov     al,dl
            and     al,0Fh
            call    print_uint16
            lea     si, msg_nl
            call    print_str  
            pop     dx
            pop     cx
            pop     bx
            pop     ax  
            pop     si
            ret


include baselib.a86

             dseg
             org     100h

month_siz    db      31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
month_day    dw      000,031,059,090,120,151,181,212,243,273,304,334
msg_interr   db      'AT BIOS interrupt error ...',13,10,0
msg_86err    db      'Not an AT class system ...',13,10,0
msg_rtc      db      'Date now: ',0
msg_ver_cc   db      'Concurrent ',0
msg_ver_hdr  db      'CP/M-86 Version ',0
msg_nl       db      13,10,0
tm_buffer    rs      256
stamp_year   rw      1
stamp_hours  rb      1
stamp_mins   rb      1
stamp_secs   rb      1
             db      0

             end
