;     The contents of this file are subject to the Mozilla Public License
;     Version 1.0 (the "License"); you may not use this file except in
;     compliance with the License. You may obtain a copy of the License at
;     http://www.mozilla.org/MPL/
;
;     Software distributed under the License is distributed on an "AS IS"
;     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
;     License for the specific language governing rights and limitations
;     under the License.

                title   'ATTIME - AT clock time Sync App'

                cseg

                mov     cx,ds
                mov     es,cx
                lea     si, msg_hdr
                call	print_str

include atclock.a86

include baselib.a86

                dseg
                org     100h
                
month_siz       db      31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
month_day       dw      000,031,059,090,120,151,181,212,243,273,304,334
msg_hdr         db      'Requesting BIOS time ...',13,10,0
msg_interr 	    db      'AT BIOS interrupt error ...',13,10,0
msg_86err 	    db      'Not an AT class system ...',13,10,0
msg_cpm31       db      'CP/M 31 ...',13,10,0
msg_nl          db      13,10,0
tm_buffer       rs      256
stamp_year      rw      1
stamp_hours     rb      1
stamp_mins      rb      1
stamp_secs      rb      1

                db      0

                end
