;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

time_read:
IF ATCLOCK
                mov     ah, 02h
                clc
                int     01Ah
                cmp     cx, 2359h
                jl      time_dec
                cmp     dh, 59h
                ja      time_read
time_dec:
                call    decode_at_time
	            jc	    int_err
                mov     ah, 04h
                clc
                int     01Ah
	            jc	    int_err
                call    decode_at_date
ELSE
                call    read_rtc_clock
ENDIF
                call    print_time
                mov     cx,0Ch
                int     0E0h
                sub     al,29H
                ja      cpm31_cpm
                call    cpm_set_time
 	            call    quit
cpm31_cpm:
                call    cpm31_set_time
 	            call    quit

IF ATCLOCK
int_86err:
	            lea	    si, msg_86err
                call	print_str
                call    quit

int_err:
	            lea	    si, msg_interr
                call	print_str
                call    quit
ENDIF

print_time:
                push    bx
                push	si
                mov     bx, 10
                mov	    ax, word ptr tm_buffer	        ; year
                call	print_dec4
                mov	    al, '-'
                call	print_char
                mov	    al, byte ptr tm_buffer+3		; month
                inc	    ax
                call	print_dec2
                mov	    al, '-'
                call	print_char
                mov	    al, byte ptr tm_buffer+2		; day
                inc	    ax
                call	print_dec2
                mov	    al, ' '
                call	print_char
                mov	    al, byte ptr tm_buffer+5		; hour
                call	print_dec2
                mov	    al, ':'
                call	print_char
                mov	    al, byte ptr tm_buffer+4		; minute
                call	print_dec2
                mov	al, ':'
                call	print_char
                mov	    al, byte ptr tm_buffer+7		; second
                call	print_dec2
                mov	al, '.'
                call	print_char
                mov	    al, byte ptr tm_buffer+6		; centisecond
                call	print_dec2
                lea	    si, msg_nl
                call	print_str
                pop	    si
                pop     bx
                ret

IF ATCLOCK
decode_at_time:
                push    ax
                push    bx
                                    ; hour
                mov     al, ch
                call    bcd_conv_byte
                mov	    byte ptr tm_buffer+5,   al
                                    ; minute
                mov     al, cl
                call    bcd_conv_byte
                mov	    byte ptr tm_buffer+4,   al
                                    ; second
                mov     al, dh
                call    bcd_conv_byte
                mov	    byte ptr tm_buffer+7,   al
                                    ; centisecond
                mov	    byte ptr tm_buffer+6,   0
                pop     ax
                pop     bx
                ret

decode_at_date:
                push    ax
                push    bx
                                    ; century
                mov     al, ch
                call    bcd_conv_byte
                mov	    byte ptr tm_buffer,   al
                                    ; year
                mov     al, cl
                call    bcd_conv_byte
                mov	    byte ptr tm_buffer+1,   al
                mov     al, byte ptr tm_buffer
                xor     ah, ah
                mov     bl, 100
                mul     bl
                mov     bl, byte ptr tm_buffer+1
                xor     bh, bh
                add     ax, bx
                mov	    word ptr tm_buffer,   ax
                                    ; month
                mov     al, dh
                call    bcd_conv_byte
                dec     al
                mov	    byte ptr tm_buffer+3,   al
                                    ; day
                mov     al, dl
                call    bcd_conv_byte
                dec     al
                mov	    byte ptr tm_buffer+2,   al
                pop     bx
                pop     ax
                ret
ELSE
read_rtc_clock:
                push    ax
                push    bx
                push    dx
                mov     dx, CPORT
                mov     al, 0Ah
                out     dx, al     
                mov     dx, DPORT
                mov     al, 20h
                out     dx, al     
                mov     dx, CPORT
                mov     al, 0Bh
                out     dx, al     
                mov     dx, DPORT
                mov     al, 27h
                out     dx, al
rtc_wait:
                mov     dx, CPORT
                mov     al, 0  ; second
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                cmp     al, 58
                jz      rtc_wait
                cmp     al, 59
                jz      rtc_wait
                mov	    byte ptr tm_buffer+7,   al
                mov	    byte ptr tm_buffer+6,   0
                mov     dx, CPORT
                mov     al, 2  ; minutes
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                mov	    byte ptr tm_buffer+4,   al
                mov     dx, CPORT
                mov     al, 4  ; hour
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                mov	    byte ptr tm_buffer+5,   al
IF DS12C887
                mov     dx, CPORT
                mov     al, 32h  ; century
                out     dx, al
ELSE
                mov     al, 20 
ENDIF
                xor     ah, ah
                mov     bl, 100
                mul     bl
                mov     bx, ax
                mov     dx, DPORT
                in      al, dx 
                mov     dx, CPORT
                mov     al, 9  ; year
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                xor     ah, ah
                add     ax, bx
                mov	    word ptr tm_buffer,   ax
                mov     dx, CPORT
                mov     al, 8  ; month
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                dec     al
                mov	    byte ptr tm_buffer+3,   al
                mov     dx, CPORT
                mov     al, 7  ; day
                out     dx, al
                mov     dx, DPORT
                in      al, dx 
                dec     al
                mov	    byte ptr tm_buffer+2,   al
                pop     dx
                pop     bx
                pop     ax
                ret
ENDIF

bcd_conv_byte:
                push    bx
                push    cx
                push    ax
                mov     cl, 04h
                ror     al, cl
                and     al, 0Fh
                mov     bl, 10
                mul     bl
                pop     bx
                and     bl, 0Fh
                add     al, bl
                pop     cx
                pop     bx
                ret

leap_days:
                push    si
                push    cx
                push    dx
                mov     cl, 2
                shr     ax, cl
                mov     dx, ax
                and     ax, 3
                jnz     leap_days_end
                lea     cx, month_day
                add     cx, bx
                add     cx, bx
                mov     si, cx
                mov     cx, [si]
                cmp     cx, 59
                jae     leap_days_end
                dec     dx
leap_days_end:
                mov     ax,dx
                pop     dx
                pop     cx
                pop     si
                ret

cpm31_set_time:
                push    es
                push    si
                push    ax
                push    bx
                push    cx
                push    dx
                ; (year-1978)*365
                mov	    ax, word ptr tm_buffer
                push    ax
                sub     ax, 1978
                mov     cx, 365
                mul     cx
                mov     dx, ax
                ; +day
                mov	    cl, byte ptr tm_buffer+2
                xor     ch, ch
                add     cl, 1
                add     dx, cx
                ; +leap_days(1978,0)
                mov     ax, 1979
                mov     bx, 0
                call    leap_days
                sub     dx, ax
                ; +month_days
                mov	    bl, byte ptr tm_buffer+3
                xor     bh, bh
                lea     cx, month_day
                add     cx, bx
                add     cx, bx
                mov     si, cx
                mov     cx, [si]
                add     dx, cx
                ; +leap_days(year, month)
                pop     ax
                mov	    bl, byte ptr tm_buffer+3
                xor     bh, bh
                call    leap_days
                add     dx, ax
                mov	    word ptr stamp_year, dx
                mov	    al, byte ptr tm_buffer+5
                xor     ah, ah
                mov     bl, 10
                div     bl
                mov     cl, 4
                rol     al, cl
                add     al, ah
                mov     byte ptr stamp_hours, al
                mov	    al, byte ptr tm_buffer+4
                xor     ah, ah
                mov     bl, 10
                div     bl
                mov     cl, 4
                rol     al, cl
                add     al, ah
                mov     byte ptr stamp_mins, al
                mov	    al, byte ptr tm_buffer+7
                xor     ah, ah
                mov     bl, 10
                div     bl
                mov     cl, 4
                rol     al, cl
                add     al, ah
                mov     byte ptr stamp_secs, al
                mov     cx,ds
                mov     es,cx
                lea     dx, stamp_year
                mov     cl, 68h
                int     0E0h
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                pop     si
                pop     es
                ret

cpm_set_time:
                push    es
                push    ax
                push    bx
                push    cx
                push    dx
                cli
                mov     cl, 31h                     ;Call Get Sysdata Addrs interrupt.
                int     0E0h                        ;CP/M interrupt. ES:BX -> Sysdata.
                add     bx, 20h                     ;ES:BX now -> 17 bytes of time/date data.
                xor     ah, ah
                mov     al, byte ptr tm_buffer+3    ;Month
                inc     al
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                inc     bx
                xor     ah, ah
                mov     al, byte ptr tm_buffer+2    ;Day
                inc     al
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                inc     bx
                xor     dx, dx
                mov     ax, word ptr tm_buffer      ;Year
                mov     cx, 100
                div     cx
                mov     ax, dx
                xor     ah, ah
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                inc     bx
                xor     ah, ah
                mov     al, byte ptr tm_buffer+5    ;Hour
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                inc     bx
                xor     ah, ah
                mov     al, byte ptr tm_buffer+4    ;Min
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                inc     bx
                xor     ah, ah
                mov     al, byte ptr tm_buffer+7    ;Sec
                mov     dl, 10
                div     dl
                add     al, '0'
                mov     es:[bx], al
                inc     bx
                mov     al, ah
                add     al, '0'
                mov     es:[bx], al
                sti
                pop     dx
                pop     cx
                pop     bx
                pop     ax
                pop     es
                ret

