;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

        title   'Clear Screen'

        cseg     
        mov     cx, cs
        mov     ds, cx
        mov     es, cx
        mov     dx, offset cls_hdr
        mov     cl,9            
        int     0E0h    
        xor     cx,cx 
        int     0E0h  
cls_hdr db      27,'E$'
        end
