;     The contents of this file are subject to the Mozilla Public License
;     Version 1.0 (the "License"); you may not use this file except in
;     compliance with the License. You may obtain a copy of the License at
;     http://www.mozilla.org/MPL/
;
;     Software distributed under the License is distributed on an "AS IS"
;     basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
;     License for the specific language governing rights and limitations
;     under the License.

                title   'Reboot'

                cseg     
                org     100h
 
                mov bx,5dh
                mov ch,0bh
                mov al,[bx]
                cmp al,57h
                jz jmp2
                cmp al,77h
                jz jmp2
                mov ax,40h
                mov ds,ax
                mov ax,0
                jmp jmp1
jmp2:
                mov ax,40h
                mov ds,ax
                mov ax,1234h
jmp1:
                mov bx,72h
                mov [bx],ax
                xor ax,ax
                mov ds,ax
                mov bx,1b8h
                mov word [bx],0
                inc bx
                inc bx
                mov word [bx],0ffffh
                int 6eh

                dseg
                end
