;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

                title   'Reboot'

reset_flag      equ 1234h
rombios_seg     equ 40h
rombios_offs    equ 72h

                cseg     
 
                mov bx,5dh
                mov ch,0bh
                mov al,[bx]
                cmp al,'W'
                jz warmboot
                cmp al,'w'
                jz warmboot
                mov ax,rombios_seg
                mov ds,ax
                mov ax,0
                jmp boot
warmboot:
                mov ax,rombios_seg
                mov ds,ax
                mov ax,reset_flag
boot:
                mov bx,rombios_offs
                mov ax,cs
                mov ds,ax
                mov bx,offset reboot_vec
                jmpf dword ptr [bx]
reboot_vec      db   0,0,0ffh,0ffh
                end
