;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

                title   'Reboot'

reset_flag      equ 1234h
rombios_data    equ 40h

                cseg     
 
                mov bx,5dh
                mov ch,0bh
                mov al,[bx]
                cmp al,'W'
                jz warmboot
                cmp al,'w'
                jz warmboot
                mov ax,rombios_data
                mov ds,ax
                mov ax,0
                jmp boot
warmboot:
                mov ax,rombios_data
                mov ds,ax
                mov ax,reset_flag
boot:
                mov bx,72h
                mov [bx],ax
                xor ax,ax
                mov ds,ax
                mov bx,1b8h
                mov word [bx],0
                inc bx
                inc bx
                mov word [bx],0ffffh
                int 6eh
                end
