;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

            title   'Skeleton'

            cseg     
            mov     cx,ds
            mov     es,cx
            mov     dx, offset msg_hdr
            mov     cl,9            
            int     0E0h    
            xor     cx,cx 
            int     0E0h  

            dseg    
msg_hdr     db      'Test',13,10,'$'
            end
