;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

            title   'Skeleton'

            cseg     
            cli
            mov     ax,ds
            mov     ss,ax
            mov     sp,offset stk + 128
            sti
            mov     cx,ds
            mov     es,cx
            mov     dx, offset msg_hdr
            mov     cl,9            
            int     0E0h    
            xor     cx,cx 
            int     0E0h  

            dseg    
msg_hdr     db      'Test',13,10,'$'
stk         rw      64              ; 128 bytes program stack
            end
