;
; Licensed under the MIT license. See LICENSE file in the project root for details.
;

                title   'ATTIME - AT clock time Sync App'

                cseg

                mov     cx,ds
                mov     es,cx
                mov     cx,0Ch
                int     0E0h
                cmp     ax,1430h
                jz      wrg_os
                cmp     ax,1431h
                jz      wrg_os
                jmp     at_time
wrg_os:
                lea	    si, msg_wrg_os
                call	print_str
                call    quit
at_time:
                lea     si, msg_hdr
                call	print_str

include clock.a86

include tinylib.a86
include baselib.a86

                dseg
                
month_siz       db      31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
month_day       dw      000,031,059,090,120,151,181,212,243,273,304,334
msg_wrg_os      db      'Not supported by this operating system.',13,10,0
msg_hdr         db      'Requesting BIOS time ...',13,10,0
msg_interr 	    db      'AT BIOS interrupt error ...',13,10,0
msg_86err 	    db      'Not an AT class system ...',13,10,0
msg_cpm31       db      'CP/M 31 ...',13,10,0
msg_nl          db      13,10,0
tm_buffer       rs      256
stamp_year      rw      1
stamp_hours     rb      1
stamp_mins      rb      1
stamp_secs      rb      1

                db      0

                end
