;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License along
;    with this program; if not, write to the Free Software Foundation, Inc.,
;    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

 
            title   'PCEINIT - Start CP/M'

include pce.a86

            cseg
            mov     cx,ds
            mov     es,cx
            call    cls
            call    print_cpm_ver
            mov     cx,0Ch
            int     0E0h
            sub     al,22H
            ja      hw_end
            call    print_hw
hw_end:
            lea     si, msg_rtc
            call    print_str

include pceclock.a86

cls:
            push    ax
            push    bx
            push    cx
            mov     dx,27
            mov     cl,02h            
            int     0E0h    
            mov     dx,'E'
            mov     cl,02h            
            int     0E0h    
            pop     cx
            pop     bx
            pop     ax
            ret

print_hw:
            push    si
            push    ax
            push    bx
            push    cx
            push    dx
            lea     si, msg_hw_hdr
            call    print_str  
            lea     si, msg_hw_mem
            call    print_str  
            int 12h
            mov     bx,10
            call    print_uint16
            lea     si, msg_hw_kb
            call    print_str  
            lea     si, msg_hw_87
            call    print_str  
            int     11h
            push    ax
            and     al,2
            jz      no_87
            lea     si, msg_hw_yes
            jmp     done_87
no_87:
            lea     si, msg_hw_no
done_87:
            call    print_str  
            lea     si, msg_hw_flp
            call    print_str  
            pop     ax
            xor     ah,ah
            mov     cl,5
            shr     al,cl
            and     al,03h
            dec     al
            mov     bx,10
            call    print_uint16
            lea     si, msg_nl
            call    print_str  
            lea     si, msg_hw_dsk
            call    print_str  
            xor     ax,ax
            mov     ah,08h
            mov     dl,80h
            int     13h
            jc      drv_2
            mov     al,dl
            xor     ah,ah
            jmp     drv_3
drv_2:
            xor     ax,ax
drv_3:
            mov     bx,10
            call    print_uint16
            lea     si, msg_nl
            call    print_str  
            pop     dx
            pop     cx
            pop     bx
            pop     ax  
            pop     si
            ret

print_cpm_ver:
            push    si
            push    ax
            push    bx
            push    cx
            push    dx
            mov     cx,0Ch
            int     0E0h
            and     ah,04h
            jz      print_ver_base
            lea     si, msg_ver_cc
            call    print_str  
print_ver_base:
            lea     si, msg_ver_hdr
            call    print_str  
            xor     ah,ah
            mov     bx,16
            mov     dl,al
            mov     cl,4
            shr     al, cl
            and     al,0Fh
            call    print_uint16
            mov     al,'.'
            call    print_char
            mov     al,dl
            and     al,0Fh
            call    print_uint16
            lea     si, msg_nl
            call    print_str  
            pop     dx
            pop     cx
            pop     bx
            pop     ax  
            pop     si
            ret

include pcelib.a86
include baselib.a86

            dseg

month_siz   db      31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
month_day   dw      000,031,059,090,120,151,181,212,243,273,304,334
msg_notpce  db      'Not running under PCE',13,10,0
msg_hookerr db      'No PCE RTC clock',13,10,0
msg_rtc     db      'Date now: ',0
msg_ver_cc  db      'Concurrent ',0
msg_ver_hdr db      'CP/M-86 Version ',0
msg_hw_hdr  db      'Hardware Configuration: ',13,10,0
msg_hw_mem  db      ' - Memory: ',0
msg_hw_87   db      ' - Math Coprocessor: ',0
msg_hw_flp  db      ' - Floppy Drive(s): ',0
msg_hw_dsk  db      ' - Hard Disk(s): ',0
msg_hw_yes  db      'Yes',13,10,0
msg_hw_no   db      'No',13,10,0
msg_hw_kb   db      'Kb',13,10,0
msg_nl      db      13,10,0
tm_buffer   rs      256
stamp_year  rw      1
stamp_hours rb      1
stamp_mins  rb      1
stamp_secs  rb      1
            db      0

            end
