;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License along
;    with this program; if not, write to the Free Software Foundation, Inc.,
;    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

 
                cseg
pce_hook_check:
	            xor	    ax, ax
                db      0D5h
                db      000h
	            sub	    ax, 0FCEh
	            jnz	    pce_hook_check_notpce
	            ret
pce_hook_check_notpce:
	            mov	    ax, 0FFFFh
	            stc
	            ret
pce_hook:
                clc
                db      0D5h
                db      000h
                ret

