;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License along
;    with this program; if not, write to the Free Software Foundation, Inc.,
;    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

 
                title   'PCEMNT - Mount Image File'

include pce.a86

                cseg

                mov     cx, ds
                mov     es, cx
                lea     si, msg_hdr
                call	print_str
	            call	pce_hook_check
	            jc	    not_pce  
                mov	    si, 80h		
                lodsb				
                mov	    cl, al
                xor	    ch, ch
                lea	    di, str1
                call	parse_opt	
                jc	    usage
                lea	    di, str2
                call	parse_opt		
                lea	    di, str1
                jc	    insert

id:
	            lea	    si, msg_id
                call    print_str
                mov     al,' '
                call    print_char
	            mov	    si, di
                call    print_str
	            lea	    si, msg_id
	            mov	    ax, pce_hook_setmsg
	            call	pce_hook		
	            jc	    hook_err
	            lea	    di, str2
                mov     al,' '
                call    print_char
insert:
	            lea	    si, msg_insert
                call    print_str
                mov     al,' '
                call    print_char
	            mov	    si, di
                call    print_str
	            lea	    si, msg_conclude
                call    print_str
	            lea	    si, msg_insert
	            mov	    ax, pce_hook_setmsg
	            call	pce_hook		
	            jc	    hook_err
	            call    quit

usage:
	            lea	    si, msg_usage
	            call	print_str
	            call    quit

not_pce:
	            lea	    si, msg_notpce
                call	print_str
                call    quit
hook_err:
	            lea	    si, msg_hookerr
                call	print_str
                call    quit

include pcelib.a86
include baselib.a86

                dseg
                org     100h

msg_id		    db      'disk.id',0
msg_insert	    db      'disk.insert',0
msg_usage	    db      'usage: pcemnt [drive] [filename]',13,10,0
msg_hdr         db      'Requesting PCE mount ...',13,10,0
msg_notpce	    db      'Not running under PCE',13,10,0
msg_hookerr 	db      'PCE Hook Error',13,10,0
msg_conclude 	db      ' ...',13,10,0
str1            rs      256
str2            rs      256
                db      0

                end
