;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License along
;    with this program; if not, write to the Free Software Foundation, Inc.,
;    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

 
                title   'PCETIME - Time Sync App'

include pce.a86

            cseg

            mov     cx,ds
            mov     es,cx
            lea     si, msg_hdr
            call    print_str

include pceclock.a86
include pcelib.a86
include baselib.a86

            dseg
            org     100h
                
month_siz   db      31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
month_day   dw      000,031,059,090,120,151,181,212,243,273,304,334
msg_hdr     db      'Requesting PCE time ...',13,10,0
msg_notpce  db      'Not running under PCE',13,10,0
msg_hookerr db      'PCE Hook Error',13,10,0
msg_cpm31   db      'CP/M 31 ...',13,10,0
msg_nl      db      13,10,0
tm_buffer   rs      256
stamp_year  rw      1
stamp_hours rb      1
stamp_mins  rb      1
stamp_secs  rb      1

            db      0

            end
